### ISSUE TITLE
Help needed for prefix/suffix 

### ISSUE THREAD

**Issue by GBatault** [Pictela/gulp-token-replace#12]
I use this Json file for config : 
but it's not replacing my tokens
any idea ?

``` json
{
  "tokens": {
    "ex":"ex"
  },
  "prefix" : "##",
  "suffix" : "##",
  "preserveUnknownTokens":true
}
```

**Comment by GBatault** [comment]
Finaly I used the Node Package : gulp-replace-task
Works better

**Comment by pictelaUK** [comment]
Apologies for a limited support over the weekend, and I'm glad you found an alternative. 

In case of future problems, please always try to submit a test case together with the configuration object. Also, have a look at the current test coverage and see if your case will return an error.

Thanks,
Martin
