### ISSUE TITLE
Re trigger by gulp.watch does not work?

### ISSUE THREAD

**Issue by fernamp** [Pictela/gulp-token-replace#18]
I've been using this plugin a lot because of its capabilities helping to avoid the repetitive tasks that can be completed with just a focused config.json file with variables. Nevertheless, as of lately, I have been trying to improve my coding routines and I've been facing some problems:

I have this in gulp.js:
```
var gulp = require('gulp'),  
    gtr = require('gulp-token-replace);  
gulp.task('default',function(){    var config = require('./config.json');
    return gulp
        .src('Temp/index.html')
        .pipe(gtr({global: config}))
        .pipe(gulp.dest('dest/'))
});
gulp.watch('./config.json',['default']);
```
A json config file like this:
```
{
    "C":{
        "A": "#ff0000,
        "B": "#ffffff",
        "C": "#000000",
        "D": "#42ae29",
        "E": "#013161"
        }
}
```
And an HTML like this:
```
<!doctype html>
<body>
    <div style="width:100px; height:100px; background:{{C.A}};">&nbsp;</div>
    <div style="width:100px; height:100px; background:{{C.B}};">&nbsp;</div>
    <div style="width:100px; height:100px; background:{{C.C}};">&nbsp;</div>
    <div style="width:100px; height:100px; background:{{C.D}};">&nbsp;</div>
    <div style="width:100px; height:100px; background:{{C.E}};">&nbsp;</div>
</body>
</html>
```
I run gulp and everything works fine, but, if I re trigger the plugin again via gulp.watch, the replacement of the values is not done and the output files is created just like the initial gulp construction.

If I stop watch and re run the process, the changes are done as expected.

Is there a way to make the plugin work with gulp.watch? Can you point me what could I do to fix the gulp.js to achieve this?

I tried everything but I'm not a programmer so is not my stronger point.

Thanks for your answer in advance!

**Comment by craftedpixels** [comment]
Place before require this
`delete require.cache[require.resolve('./path2content.json')];`

**Comment by fernamp** [comment]
That fixed it!!!! Thanks a lot!
