### ISSUE TITLE
Not finding and replacing my token.

### ISSUE THREAD

**Issue by jeremyhodges** [Pictela/gulp-token-replace#8]
settings.json:

```
{
  "tokens" : {
    "baseUrl": "(/dev.www.backyardfruit.com/someimage.jpg)",
    "next": "something else"
  }
}
```

gulpfile:

```
var tokenize = require('gulp-token-replace');
var settings = require('./settings.json');

  return gulp.src('./source/static.me.com/**/*.css')
    .pipe(tokenize({global:settings, preserveUnknownTokens: true}))
    .pipe(sourcemaps.init())
    .pipe(concat('mycss.css'))
    .pipe(minify())
    .pipe(sourcemaps.write())
    .pipe(rename('mycss.min.css'))
    .pipe(gulp.dest('./build/static.me.com/css'));
```

css file:

```
.url {
  background-image: {{ baseUrl }}
}
```

I also tried:

```
.url {
  background-image: {{ tokens.baseUrl }}
}
```

**Comment by pictelaUK** [comment]
Hey, 

Thanks for the query. 

First and foremost I would recommend checking the CSS syntax for background-image, as the url() seems to be missing. 

`"baseUrl":"url(/dev.www.backyardfruit.com/someimage.jpg)"`

It works quite well with SASS: 

`return gulp.src(files)
    .pipe(replace({global:config}))
    .pipe(sass())
    .pipe(minifyCSS())
    .pipe(flatten())
    .pipe(gulp.dest(dist))
    .pipe(livereload())`

SASS: 
`#url {
  bacground-image: {{tokens.baseUrl}};
}`

OUTPUT: 
`#url{bacground-image:url(/dev.www.backyardfruit.com/someimage.jpg)}`

Please check and let me know.

**Comment by jeremyhodges** [comment]
@pictelaUK Looks like I found the issue. I had spaces between the double brackets. Once I removed those spaces everything started working.
